<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Automotive e-commerce analytics [STEP 1]</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="[STEP 1] Data Cleaning_files/libs/clipboard/clipboard.min.js"></script>
<script src="[STEP 1] Data Cleaning_files/libs/quarto-html/quarto.js"></script>
<script src="[STEP 1] Data Cleaning_files/libs/quarto-html/popper.min.js"></script>
<script src="[STEP 1] Data Cleaning_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="[STEP 1] Data Cleaning_files/libs/quarto-html/anchor.min.js"></script>
<link href="[STEP 1] Data Cleaning_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="[STEP 1] Data Cleaning_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="[STEP 1] Data Cleaning_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="[STEP 1] Data Cleaning_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="[STEP 1] Data Cleaning_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Automotive e-commerce analytics [STEP 1]</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The current task is to analyze the datasets provided and extract actionable insights that can help the company optimize its sales strategy across different platforms.</p>
<section id="import-the-libraries" class="level2">
<h2 class="anchored" data-anchor-id="import-the-libraries">1) Import the libraries</h2>
<div id="cell-4" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># custom library</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> grafici</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="define-useful-variables" class="level2">
<h2 class="anchored" data-anchor-id="define-useful-variables">1.1) Define useful variables</h2>
<div id="cell-6" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>cars <span class="op">=</span> pd.read_csv(<span class="st">'Raw_Data/cars.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sales <span class="op">=</span> pd.read_csv(<span class="st">'Raw_Data/sales.csv'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>users <span class="op">=</span> pd.read_csv(<span class="st">'Raw_Data/users.csv'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>visits <span class="op">=</span> pd.read_csv(<span class="st">'Raw_Data/visits.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="analyze-each-file" class="level2">
<h2 class="anchored" data-anchor-id="analyze-each-file">2) Analyze each file</h2>
<p>Now we are going to give a fast overview of the avaiable data, the current objective is to clean all the data based on what we expect to be</p>
</section>
<section id="cars" class="level2">
<h2 class="anchored" data-anchor-id="cars">2.1) Cars</h2>
<ul>
<li><code>car_id</code>: Unique identifier for the car.</li>
<li><code>car_model</code>: Model of the car.</li>
<li><code>fuel_type</code>: Fuel type of the car.</li>
<li><code>release_date</code>: Date when the car was released.</li>
<li><code>price</code>: Base price of the car.</li>
</ul>
<div id="cell-11" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>cars.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>(12, 5)</code></pre>
</div>
</div>
<p>Ok now we know that we don’t have that many cars, so if we find something wrong we cannot delete any given row</p>
<div id="cell-13" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># thanks to the small size of the data, we can easily see the data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>cars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">car_id</th>
<th data-quarto-table-cell-role="th">car_model</th>
<th data-quarto-table-cell-role="th">fuel_type</th>
<th data-quarto-table-cell-role="th">release_date</th>
<th data-quarto-table-cell-role="th">price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2c192c40-f69f-42e5-9431-41d92558568b</td>
<td>Sierra</td>
<td>Diesel</td>
<td>2013-05-01</td>
<td>35000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>d2e63c70-e732-4299-bb0c-ba00b875a4bd</td>
<td>3 Series</td>
<td>Diesel</td>
<td>2014-12-11</td>
<td>40000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>00b0c76e-9f2f-41c1-8324-38fbe9c2a8aa</td>
<td>Model i8</td>
<td>Electric</td>
<td>2019-01-01</td>
<td>145000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4abc60d6-73cb-44df-8bde-d8f5936bbdfb</td>
<td>Coupe</td>
<td>Gasoline</td>
<td>2015-08-01</td>
<td>65000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5fae80e1-82d6-45d3-8512-7db7bb32d5bd</td>
<td>Sedan</td>
<td>Gasoline</td>
<td>2018-07-15</td>
<td>45000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>4c20c5ec-0d42-46ac-ae0f-cbafeceaca32</td>
<td>Model i7</td>
<td>Electric</td>
<td>2015-03-01</td>
<td>120000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>ab72e1ef-639f-4ad0-b9b0-28a50f3c7229</td>
<td>Model iX</td>
<td>Electric</td>
<td>2017-11-10</td>
<td>131000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>eee54c45-64fe-462b-b9c2-e23adea76282</td>
<td>1 Series</td>
<td>Diesel</td>
<td>2010-10-01</td>
<td>30000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>42a26053-2d52-4926-b19c-ddd4b82c3e75</td>
<td>Touring</td>
<td>Gasoline</td>
<td>2019-02-01</td>
<td>90000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>0c048ea4-5e29-419e-a448-99f75742117c</td>
<td>Model M</td>
<td>Gasoline</td>
<td>2016-04-01</td>
<td>70000</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">10</td>
<td>c571bf78-719f-451e-8cdb-f8bc7376053e</td>
<td>Model iY</td>
<td>Electric</td>
<td>2014-09-01</td>
<td>72000</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">11</td>
<td>0a441025-806f-402e-8699-d7eb988c671f</td>
<td>Tourer</td>
<td>Gasoline</td>
<td>2017-11-01</td>
<td>60000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="data-checks" class="level3">
<h3 class="anchored" data-anchor-id="data-checks">2.1.1) Data checks</h3>
<p>we need now to ensure that the data is clean and the staements are been respected</p>
<div id="cell-16" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we can start by checking if there is any null values in the data</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>cars.isnull().<span class="bu">sum</span>().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>0</code></pre>
</div>
</div>
<div id="cell-17" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># now we can check the data types of the columns</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>cars.dtypes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>car_id          object
car_model       object
fuel_type       object
release_date    object
price            int64
dtype: object</code></pre>
</div>
</div>
<div id="cell-18" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert the release_date column to datetime</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>cars[<span class="st">'release_date'</span>] <span class="op">=</span> pd.to_datetime(cars[<span class="st">'release_date'</span>])  <span class="co"># we're going to re-apply this in the next notebook</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-19" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check that all the car_id are unique</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>cars[<span class="st">'car_id'</span>].nunique() <span class="op">==</span> cars.shape[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>True</code></pre>
</div>
</div>
<div id="cell-20" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># just to be sure we can now check the number of unique values in the other columns</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>cars.nunique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>car_id          12
car_model       12
fuel_type        3
release_date    12
price           12
dtype: int64</code></pre>
</div>
</div>
<p>Everything seems right, now we can save the cleaned data to analyze it later</p>
</section>
<section id="null-analysis" class="level3">
<h3 class="anchored" data-anchor-id="null-analysis">2.1.2) Null analysis</h3>
<div id="cell-23" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nulls</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>cars.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>car_id          0
car_model       0
fuel_type       0
release_date    0
price           0
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="save-the-cleaned-data" class="level3">
<h3 class="anchored" data-anchor-id="save-the-cleaned-data">2.1.2) Save the cleaned data</h3>
<div id="cell-25" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># save the cleaned data</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>cars.to_csv(<span class="st">'Cleaned_Data/cars.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="sales" class="level2">
<h2 class="anchored" data-anchor-id="sales">2.2) Sales</h2>
<ul>
<li><code>transaction_id</code>: Unique identifier for the purchase.</li>
<li><code>customer_id</code>: Identifier for the user who made the purchase.</li>
<li><code>car_id</code>: Identifier for the car that was purchased.</li>
<li><code>platform</code>: Platform on which the purchase was made.</li>
<li><code>purchase_date</code>: Date when the purchase was made.</li>
<li><code>purchase_price</code>: Final price at which the car was sold after any discounts.</li>
<li><code>user_review</code>: An optional user review (as a score) given for the platform after each purchase.</li>
</ul>
<div id="cell-28" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># shape</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>sales.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<pre><code>(74836, 7)</code></pre>
</div>
</div>
<p>In this case we cannot view all the data given the high number of rows, we need to proceed by steps</p>
<div id="cell-30" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sales.head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">transaction_id</th>
<th data-quarto-table-cell-role="th">customer_id</th>
<th data-quarto-table-cell-role="th">car_id</th>
<th data-quarto-table-cell-role="th">platform</th>
<th data-quarto-table-cell-role="th">purchase_date</th>
<th data-quarto-table-cell-role="th">purchase_price</th>
<th data-quarto-table-cell-role="th">user_review</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>d8ea7895-4dda-4419-9291-5fe446c8d387</td>
<td>d4a436e4-938c-4281-9c9c-5912be025b19</td>
<td>5fae80e1-82d6-45d3-8512-7db7bb32d5bd</td>
<td>Website</td>
<td>2021-10-14</td>
<td>45000.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>73bba083-92ea-4580-80ef-527193c8a897</td>
<td>1105c980-82a0-4296-8de0-fcb37fbdd435</td>
<td>eee54c45-64fe-462b-b9c2-e23adea76282</td>
<td>Dealership</td>
<td>2022-11-03</td>
<td>30000.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>4150e505-a55e-4eb8-b321-92ed2e96553e</td>
<td>8c987376-6996-4137-977a-5415b81b55d0</td>
<td>ab72e1ef-639f-4ad0-b9b0-28a50f3c7229</td>
<td>Website</td>
<td>2023-12-14</td>
<td>131000.0</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>5bf1dbeb-6469-4b77-accd-4af5ce6a48a2</td>
<td>9289286a-dece-4d9c-9d64-fafd949f7fb0</td>
<td>0c048ea4-5e29-419e-a448-99f75742117c</td>
<td>Dealership</td>
<td>2023-02-14</td>
<td>70000.0</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>e7e61ff9-0ac3-4101-b195-369faa256f79</td>
<td>ba30d504-d66f-4879-8af3-999884f2e0f8</td>
<td>eee54c45-64fe-462b-b9c2-e23adea76282</td>
<td>Dealership</td>
<td>2022-07-04</td>
<td>30000.0</td>
<td>1.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="data-checks-1" class="level3">
<h3 class="anchored" data-anchor-id="data-checks-1">2.2.1) Data checks</h3>
<p>During the exploration i found out that some values instead of being none they were “data layer field missing” so first of all we want to convert them to np.nan</p>
<div id="cell-33" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using regex search to find all the values that hasn't this pattern: string-string-string-string-string </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to be able to to that we need to fill the NaN values with an empty string</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>sales[<span class="op">~</span>sales[<span class="st">'customer_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"customer_id"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>customer_id
data layer field missing    13
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-34" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>sales[<span class="op">~</span>sales[<span class="st">'transaction_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"transaction_id"</span>].value_counts() <span class="co"># no strange values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Series([], Name: count, dtype: int64)</code></pre>
</div>
</div>
<div id="cell-35" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>sales[<span class="op">~</span>sales[<span class="st">'car_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"car_id"</span>].value_counts() <span class="co"># no strange values</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>Series([], Name: count, dtype: int64)</code></pre>
</div>
</div>
<p>As we can see the only value that isn’t following the correct pattern is “data layer field missing”, we can now replace it with np.nan</p>
<div id="cell-37" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># replace the value "data layer field missing" with NaN</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>sales <span class="op">=</span> sales.replace(<span class="st">"data layer field missing"</span>, np.nan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-38" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the unique values of the platform column</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'platform'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>platform
Dealership    36306
Mobile App    23967
Website       14563
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-39" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'purchase_date'</span>] <span class="op">=</span> pd.to_datetime(sales[<span class="st">'purchase_date'</span>])</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the distribution of the purchase_date by year</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'purchase_date'</span>].dt.year.value_counts().sort_index().plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>), title<span class="op">=</span><span class="st">'Distribution of the purchase_date by year'</span>)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the distribution of the purchase_date by month</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'purchase_date'</span>].dt.month.value_counts().sort_index().plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>), title<span class="op">=</span><span class="st">'Distribution of the purchase_date by month'</span>)</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the distribution of the purchase_date by day</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'purchase_date'</span>].dt.day.value_counts().sort_index().plot(kind<span class="op">=</span><span class="st">'bar'</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>), title<span class="op">=</span><span class="st">'Distribution of the purchase_date by day'</span>)</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-20-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-20-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-40" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># boxplot for the purchase_price column</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'purchase_price'</span>].plot(kind<span class="op">=</span><span class="st">'box'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-21-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-41" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># boxplot for the user_review column</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>sales[<span class="st">'user_review'</span>].plot(kind<span class="op">=</span><span class="st">'box'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-22-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Everything seems ok</p>
</section>
<section id="null-analysis-1" class="level3">
<h3 class="anchored" data-anchor-id="null-analysis-1">2.2.2) Null analysis</h3>
<div id="cell-44" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print all the nulls</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>sales.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>transaction_id       24
customer_id          37
car_id                0
platform              0
purchase_date         0
purchase_price       32
user_review       65070
dtype: int64</code></pre>
</div>
</div>
<p>We can see that the “user_review” column contains a lot of missing data, but that’s ok</p>
<p>The others null are suspicious, we need to investigate them</p>
<div id="cell-46" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print all the rows that have transaction_id as null</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>sales[sales[<span class="st">'transaction_id'</span>].isnull()]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">transaction_id</th>
<th data-quarto-table-cell-role="th">customer_id</th>
<th data-quarto-table-cell-role="th">car_id</th>
<th data-quarto-table-cell-role="th">platform</th>
<th data-quarto-table-cell-role="th">purchase_date</th>
<th data-quarto-table-cell-role="th">purchase_price</th>
<th data-quarto-table-cell-role="th">user_review</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">7122</td>
<td>NaN</td>
<td>d1b9e561-b376-4162-9efe-cd41c950f519</td>
<td>2c192c40-f69f-42e5-9431-41d92558568b</td>
<td>Mobile App</td>
<td>2020-09-11</td>
<td>145000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7521</td>
<td>NaN</td>
<td>f116dfeb-4db4-46bb-84c3-810b4091092d</td>
<td>0c048ea4-5e29-419e-a448-99f75742117c</td>
<td>Mobile App</td>
<td>2020-11-25</td>
<td>120000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">11091</td>
<td>NaN</td>
<td>NaN</td>
<td>5fae80e1-82d6-45d3-8512-7db7bb32d5bd</td>
<td>Mobile App</td>
<td>2020-10-29</td>
<td>60000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">12341</td>
<td>NaN</td>
<td>NaN</td>
<td>4abc60d6-73cb-44df-8bde-d8f5936bbdfb</td>
<td>Mobile App</td>
<td>2021-05-08</td>
<td>65000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">22893</td>
<td>NaN</td>
<td>NaN</td>
<td>2c192c40-f69f-42e5-9431-41d92558568b</td>
<td>Mobile App</td>
<td>2021-07-12</td>
<td>65000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">35093</td>
<td>NaN</td>
<td>91dfa073-e856-47c1-85b6-61ee84130b52</td>
<td>0c048ea4-5e29-419e-a448-99f75742117c</td>
<td>Mobile App</td>
<td>2021-04-05</td>
<td>30000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">41219</td>
<td>NaN</td>
<td>1d6caf85-40ce-409a-84fb-f6efdb5d4fe8</td>
<td>eee54c45-64fe-462b-b9c2-e23adea76282</td>
<td>Mobile App</td>
<td>2021-03-23</td>
<td>70000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">42738</td>
<td>NaN</td>
<td>NaN</td>
<td>2c192c40-f69f-42e5-9431-41d92558568b</td>
<td>Mobile App</td>
<td>2021-01-19</td>
<td>35000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">44725</td>
<td>NaN</td>
<td>NaN</td>
<td>2c192c40-f69f-42e5-9431-41d92558568b</td>
<td>Mobile App</td>
<td>2021-08-03</td>
<td>131000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">47858</td>
<td>NaN</td>
<td>NaN</td>
<td>c571bf78-719f-451e-8cdb-f8bc7376053e</td>
<td>Mobile App</td>
<td>2020-12-08</td>
<td>70000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">51210</td>
<td>NaN</td>
<td>NaN</td>
<td>4abc60d6-73cb-44df-8bde-d8f5936bbdfb</td>
<td>Mobile App</td>
<td>2021-01-06</td>
<td>120000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">51461</td>
<td>NaN</td>
<td>NaN</td>
<td>d2e63c70-e732-4299-bb0c-ba00b875a4bd</td>
<td>Mobile App</td>
<td>2021-06-11</td>
<td>35000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">51559</td>
<td>NaN</td>
<td>76f17208-06c8-4777-addd-17a506802c0f</td>
<td>42a26053-2d52-4926-b19c-ddd4b82c3e75</td>
<td>Website</td>
<td>2021-08-15</td>
<td>145000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">52099</td>
<td>NaN</td>
<td>NaN</td>
<td>5fae80e1-82d6-45d3-8512-7db7bb32d5bd</td>
<td>Mobile App</td>
<td>2021-04-07</td>
<td>65000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">53124</td>
<td>NaN</td>
<td>NaN</td>
<td>00b0c76e-9f2f-41c1-8324-38fbe9c2a8aa</td>
<td>Mobile App</td>
<td>2021-06-20</td>
<td>40000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">54421</td>
<td>NaN</td>
<td>ecc42089-1fd8-4e36-960b-9720d5e16cee</td>
<td>5fae80e1-82d6-45d3-8512-7db7bb32d5bd</td>
<td>Mobile App</td>
<td>2021-03-05</td>
<td>30000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">59722</td>
<td>NaN</td>
<td>NaN</td>
<td>00b0c76e-9f2f-41c1-8324-38fbe9c2a8aa</td>
<td>Website</td>
<td>2021-05-11</td>
<td>40000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">59754</td>
<td>NaN</td>
<td>NaN</td>
<td>4c20c5ec-0d42-46ac-ae0f-cbafeceaca32</td>
<td>Website</td>
<td>2020-11-05</td>
<td>120000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">60640</td>
<td>NaN</td>
<td>NaN</td>
<td>42a26053-2d52-4926-b19c-ddd4b82c3e75</td>
<td>Mobile App</td>
<td>2021-03-25</td>
<td>70000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">61562</td>
<td>NaN</td>
<td>829747cf-d856-4f91-8324-1e4fcff8b2d6</td>
<td>eee54c45-64fe-462b-b9c2-e23adea76282</td>
<td>Mobile App</td>
<td>2021-07-02</td>
<td>30000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">61655</td>
<td>NaN</td>
<td>NaN</td>
<td>5fae80e1-82d6-45d3-8512-7db7bb32d5bd</td>
<td>Mobile App</td>
<td>2020-10-07</td>
<td>72000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">63124</td>
<td>NaN</td>
<td>NaN</td>
<td>d2e63c70-e732-4299-bb0c-ba00b875a4bd</td>
<td>Website</td>
<td>2020-08-28</td>
<td>65000.0</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">69618</td>
<td>NaN</td>
<td>61a74738-2f26-4b9e-98c8-0195f62e5f0b</td>
<td>eee54c45-64fe-462b-b9c2-e23adea76282</td>
<td>Mobile App</td>
<td>2021-01-19</td>
<td>35000.0</td>
<td>0.0</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">73611</td>
<td>NaN</td>
<td>NaN</td>
<td>0c048ea4-5e29-419e-a448-99f75742117c</td>
<td>Mobile App</td>
<td>2021-07-11</td>
<td>70000.0</td>
<td>0.0</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Based on this we can see that besides the “data layer field missing” strange value, the rows have almost all the other fields populated, for now we are going to keep them (we can get the hash from the visits)</p>
<p>After some investigation i’ve decided that given the restricted time that i got and the huge amount of data we can drop the nan’s value (if i had more time i would try to get those info by merging the tables or with a KNN for the price)</p>
<div id="cell-48" class="cell" data-execution_count="24">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>rows_removed <span class="op">=</span> <span class="bu">len</span>(sales) <span class="op">-</span> <span class="bu">len</span>(sales.dropna(subset<span class="op">=</span>[<span class="st">'transaction_id'</span>, <span class="st">'customer_id'</span>, <span class="st">'car_id'</span>]))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Number of rows removed: </span><span class="sc">{</span>rows_removed<span class="sc">}</span><span class="ss">, </span><span class="ch">\n</span><span class="ss">percentage: </span><span class="sc">{</span>rows_removed<span class="op">/</span><span class="bu">len</span>(sales)<span class="op">*</span><span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of rows removed: 45, 
percentage: 0.06%</code></pre>
</div>
</div>
<div id="cell-49" class="cell" data-execution_count="25">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop the rows with null values</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>sales <span class="op">=</span> sales.dropna(subset<span class="op">=</span>[<span class="st">'transaction_id'</span>, <span class="st">'customer_id'</span>, <span class="st">'purchase_price'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-50" class="cell" data-execution_count="26">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print all the remaining nulls</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>sales.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>transaction_id        0
customer_id           0
car_id                0
platform              0
purchase_date         0
purchase_price        0
user_review       65070
dtype: int64</code></pre>
</div>
</div>
<div id="cell-51" class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># save the cleaned data</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>sales.to_csv(<span class="st">'Cleaned_Data/sales.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="users" class="level2">
<h2 class="anchored" data-anchor-id="users">2.3) Users</h2>
<ul>
<li><code>customer_id</code>: Unique identifier for the user.</li>
<li><code>user_first_name</code>: First name of the user.</li>
<li><code>user_last_name</code>: Last name of the user.</li>
<li><code>gender</code>: Gender of the user.</li>
<li><code>email</code>: Email address of the user.</li>
</ul>
<div id="cell-54" class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>users.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="28">
<pre><code>(138678, 5)</code></pre>
</div>
</div>
<div id="cell-55" class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>users.head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">customer_id</th>
<th data-quarto-table-cell-role="th">user_first_name</th>
<th data-quarto-table-cell-role="th">user_last_name</th>
<th data-quarto-table-cell-role="th">gender</th>
<th data-quarto-table-cell-role="th">email</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>414970e2-b5c8-43a5-a91b-c5557b9dbec0</td>
<td>Dwayne</td>
<td>Romero</td>
<td>Male</td>
<td>romero@gmail.com</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>504db575-40df-44e1-806d-16777c2dd6e0</td>
<td>Madison</td>
<td>Burgess</td>
<td>Female</td>
<td>burgess@yahoo.com</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>42af527d-454a-465e-9a74-42d4b174a49e</td>
<td>Kristin</td>
<td>Castro</td>
<td>Female</td>
<td>kristin1992@hotmail.com</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>38dda2e0-61f6-4d63-9427-f5055c9258ff</td>
<td>Jessica</td>
<td>Taylor</td>
<td>Female</td>
<td>jessica@hotmail.com</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>19936993-0480-4399-ab80-9aca3e282d07</td>
<td>Cody</td>
<td>King</td>
<td>Male</td>
<td>king@hotmail.com</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="data-checks-2" class="level3">
<h3 class="anchored" data-anchor-id="data-checks-2">2.3.1) Data checks</h3>
<div id="cell-57" class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check with the regex search if there are any strange values in the user_id column</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>users[<span class="op">~</span>users[<span class="st">'customer_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"customer_id"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>customer_id
data layer field missing    286
Name: count, dtype: int64</code></pre>
</div>
</div>
<div id="cell-58" class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># even here we can see that there is the value "data layer field missing" that we can replace with NaN</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>users <span class="op">=</span> users.replace(<span class="st">"data layer field missing"</span>, np.nan)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-59" class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the distribution of the user_first_name column</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>grafici.plot_categorical_column(users, <span class="st">'user_first_name'</span>, <span class="st">"lightblue"</span>, min_percentile<span class="op">=</span><span class="dv">93</span>, max_percentile<span class="op">=</span><span class="dv">100</span>, hide_outliers<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>), anomaly_threshold<span class="op">=</span><span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Categorie per Frequenza:
Frequenza 1: Maximilian, Simon
Frequenza 12: Leroy, Terrance
Frequenza 13: Darin, Perry, Stuart, Wyatt
Frequenza 14: Gene, Gilbert, Leon
Frequenza 15: Diamond, Franklin, Lonnie
Frequenza 16: Isabel, Max, Preston, Rickey, Warren
Frequenza 17: Angie, Dave, Gregg, Herbert, Neil, Vernon
Frequenza 18: Brady, Cristina, Gordon, Guy
Frequenza 19: Alvin, Bernard, Daryl, Tami, Terrence, Yesenia, Zoe
Frequenza 20: Darius, Earl, Hayden, Karl, Malik, Marco, Mindy, Nina, Parker, Priscilla, Tracie
Frequenza 21: Bob, Cesar, Faith, Glenda, Kent, Mia, Pedro, Sally
Frequenza 22: Alfred, Francis, Latasha, Lorraine, Mercedes, Ross
Frequenza 23: Clarence, Doris, Gavin, Jermaine, Karla, Kellie, Kerri, Norman, Sonia, Stefanie
Frequenza 24: Cassie, Gwendolyn, Kiara, Lydia, Mandy, Maxwell, Patty, Ray, Riley, Sheena
Frequenza 25: Damon, Dan, Dominic, Glen, Jackson, Jasmin, Kristie, Marisa, Melody, Nicolas, Rick, Robyn, Shelia
Frequenza 26: Don, Isabella, Ivan, Raven, Shawna, Sue
Frequenza 27: Alejandra, Bryce, Cole, Daisy, Devon, Lacey, Phyllis
Frequenza 28: Aimee, Chelsey, Collin, Frances, Joann, Kirk, Levi, Mckenzie, Shari, Tammie
Frequenza 29: Adriana, Bill, Carly, Cristian, Eduardo, Gabriela, Kirsten, Stacie, Xavier
Frequenza 30: Christie, Edgar, Geoffrey, Kylie, Marcia
Frequenza 31: Alec, Andres, Caitlyn, Dillon, Makayla, Selena
Frequenza 32: Charlene, Gabriella, Jaclyn, Jo, Tabitha, Tasha, Tricia, Tristan
Frequenza 33: Clayton, Ebony, Fernando, Fred, Roberta, Sandy, Sheryl, Tyrone
Frequenza 34: Cassidy, Mason, Pam, Sergio
Frequenza 35: Alice, Alisha, Jocelyn, Loretta, Mikayla, Summer, Yvette
Frequenza 36: Ariel, Dalton, Duane, Elaine, Elijah, Greg, Jade, Sophia, Tom
Frequenza 37: Ariana, Belinda, Clifford, Eileen, Karina, Norma
Frequenza 38: Jim, Kristopher
Frequenza 39: Drew, Helen, Jeanne, Mathew, Ruben
Frequenza 40: Alexa, Charlotte, Colton, Dominique, Kaylee
Frequenza 41: Jackie
Frequenza 42: Bianca, Candace, Chloe, Clinton, Jerome, Omar
Frequenza 43: Claire, Hayley, Kerry, Maurice
Frequenza 44: Dorothy, Tanner
Frequenza 45: Darryl, Jean, Joan, Latoya, Stanley, Vickie
Frequenza 46: Gail, Julian, Maureen, Ralph, Theodore, Tim
Frequenza 47: Ashlee, Grant, Howard, Jake, Jody, Kaitlin, Mallory
Frequenza 48: Harry, Meagan, Rose
Frequenza 49: Hailey, Marvin, Melvin, Michaela
Frequenza 50: Brad, Ernest, Javier, Jeanette, Kurt, Lance
Frequenza 51: Adrienne, Bailey, Brendan, Dwayne, Marilyn, Shaun
Frequenza 52: Colin, Isaiah, Rebekah
Frequenza 53: Bridget, Cheyenne, Grace, Kristine, Meredith
Frequenza 54: Breanna, Eugene, Leonard, Rita, Ruth
Frequenza 55: Mackenzie, Penny, Vicki
Frequenza 56: Candice, Ellen, Kelli
Frequenza 57: Briana, Carmen, Harold, Jonathon, Mariah, Sierra, Sylvia
Frequenza 58: Alexandria, Dakota, Hector, Joanne, Joy, Ronnie
Frequenza 60: Dean, Spencer
Frequenza 61: Becky, Betty, Evelyn, Madeline, Sheri
Frequenza 62: Chase, Claudia, Connor, Jillian
Frequenza 63: Peggy, Savannah
Frequenza 64: Toni
Frequenza 65: Desiree, Eddie, Hunter, Jenny, Tommy
Frequenza 66: Ana, Johnathan, Oscar, Ricardo
Frequenza 67: Joyce, Nichole, Noah, Roberto, Shelley
Frequenza 68: Alejandro
Frequenza 69: Reginald, Traci
Frequenza 70: Destiny, Kristy
Frequenza 71: Judith, Shirley, Yvonne
Frequenza 72: Barry, Beverly, Frederick
Frequenza 73: Jane, Lee
Frequenza 74: Audrey, Edwin, Kari, Martha
Frequenza 75: Glenn
Frequenza 76: Autumn, Bethany, Wanda
Frequenza 77: Calvin, Paige
Frequenza 78: Bonnie, Darlene, Darrell, Francisco, Gloria, Isaac, Kristi, Sonya
Frequenza 79: Angelica, Dale, Mike
Frequenza 80: Caroline, Joanna, Manuel
Frequenza 81: Roy, Steve
Frequenza 82: Darren, Jodi, Krystal, Mario, Monique
Frequenza 83: Chris, Devin
Frequenza 84: Anita, Jaime, Lucas
Frequenza 85: Ethan, Jeremiah, Krista, Sherri
Frequenza 86: Janice, Micheal, Tracey, Yolanda
Frequenza 87: Louis, Sydney
Frequenza 88: Albert, Shelly
Frequenza 89: Emma, Gabrielle
Frequenza 90: Jeff, Rachael
Frequenza 91: Garrett, Judy, Kara, Katelyn
Frequenza 92: Blake, Logan, Luke
Frequenza 93: Annette
Frequenza 95: Marissa
Frequenza 96: Jorge
Frequenza 97: Miguel
Frequenza 100: Jesus
Frequenza 101: Cathy, Derrick, Kaitlyn
Frequenza 102: Marc, Seth
Frequenza 103: Meghan, Whitney
Frequenza 104: Alison, Arthur, Kendra, Willie
Frequenza 105: Adrian, Joe
Frequenza 106: Trevor
Frequenza 107: Jay
Frequenza 108: Wesley
Frequenza 109: Andre, Lynn, Natasha
Frequenza 112: Bruce
Frequenza 113: Allen, Billy, Shelby
Frequenza 114: Brittney, Christy, Evan, Felicia, Gerald, Virginia
Frequenza 115: Debbie, Molly, Wayne
Frequenza 116: Cameron
Frequenza 117: Carla, Colleen, Marie, Randall
Frequenza 118: Bobby, Jimmy, Jon, Katrina, Laurie, Lawrence, Walter
Frequenza 119: Gabriel
Frequenza 120: Caleb, Ian, Jack, Misty, Terri
Frequenza 121: Connie
Frequenza 122: Johnny, Miranda
Frequenza 123: Caitlin, Mitchell, Sabrina
Frequenza 125: Ricky
Frequenza 126: Abigail, Brandi, Cory
Frequenza 128: Deanna
Frequenza 129: Haley
Frequenza 130: Carl, Danny, Roger
Frequenza 131: Madison
Frequenza 133: Jenna
Frequenza 134: Suzanne
Frequenza 135: Olivia, Rodney, Russell
Frequenza 137: Erika, Martin
Frequenza 138: Angel, Erik
Frequenza 139: Nathaniel
Frequenza 140: Corey
Frequenza 143: Henry
Frequenza 144: Brent, Curtis, Regina, Tamara, Tanya
Frequenza 145: Beth, Melinda
Frequenza 146: Leah
Frequenza 147: Anne, Antonio
Frequenza 150: Brooke, Heidi, Tony
Frequenza 154: Jared
Frequenza 157: Brett, Sheila
Frequenza 158: Victor
Frequenza 159: Joel, Kelsey, Lindsay, Sherry
Frequenza 161: Morgan
Frequenza 162: Philip
Frequenza 163: Kristina
Frequenza 164: Tonya
Frequenza 167: Dylan, Jeffery, Kim
Frequenza 168: Katie
Frequenza 169: Alex, Luis
Frequenza 171: Stacey
Frequenza 172: Brianna
Frequenza 173: Brandy
Frequenza 176: Alan
Frequenza 177: Vincent
Frequenza 178: Cassandra
Frequenza 179: Lindsey, Paula
Frequenza 181: Casey
Frequenza 183: Carlos, Janet
Frequenza 185: Christian
Frequenza 186: Rhonda
Frequenza 187: Kathy
Frequenza 188: Carolyn, Diane
Frequenza 189: Gina, Shane
Frequenza 191: Randy
Frequenza 192: Carol
Frequenza 194: Renee
Frequenza 195: Alexandra
Frequenza 196: Chelsea
Frequenza 198: Marcus
Frequenza 199: Ann
Frequenza 200: Carrie, Dustin
Frequenza 202: Jerry
Frequenza 207: Troy
Frequenza 212: Frank, Jill, Valerie, Veronica
Frequenza 214: Theresa
Frequenza 216: Phillip
Frequenza 220: Jasmine, Tara
Frequenza 222: Allison, Derek
Frequenza 224: Dennis
Frequenza 225: Juan
Frequenza 228: Terry
Frequenza 229: Diana
Frequenza 232: Stacy
Frequenza 235: Austin, Cindy
Frequenza 238: Larry
Frequenza 240: Alicia, Craig
Frequenza 242: Alyssa, Melanie
Frequenza 243: Todd
Frequenza 245: Dana
Frequenza 247: Holly, Michele, Raymond
Frequenza 251: Julia
Frequenza 253: Natalie
Frequenza 254: Alexis
Frequenza 255: Cheryl
Frequenza 257: Hannah
Frequenza 258: Wendy
Frequenza 259: Cody
Frequenza 263: Jesse
Frequenza 266: Bradley
Frequenza 272: Kristin
Frequenza 273: Vanessa
Frequenza 277: Debra
Frequenza 278: Margaret
Frequenza 283: Monica
Frequenza 287: Leslie
Frequenza 288: Kathryn
Frequenza 289: Anna
Frequenza 294: Travis
Frequenza 295: Robin
Frequenza 301: April
Frequenza 302: George
Frequenza 303: Bryan, Keith
Frequenza 305: Chad
Frequenza 308: Douglas, Shawn
Frequenza 310: Jacqueline
Frequenza 312: Kayla
Frequenza 316: Erica
Frequenza 321: Catherine
Frequenza 323: Kristen
Frequenza 325: Peter
Frequenza 326: Barbara
Frequenza 332: Nathan
Frequenza 333: Jordan
Frequenza 334: Samuel
Frequenza 337: Nancy
Frequenza 338: Gary
Frequenza 339: Erin
Frequenza 340: Tina
Frequenza 341: Alexander
Frequenza 344: Dawn
Frequenza 347: Kathleen
Frequenza 348: Sharon, Teresa
Frequenza 349: Denise, Taylor
Frequenza 351: Deborah
Frequenza 356: Courtney
Frequenza 357: Jose
Frequenza 364: Victoria
Frequenza 370: Donna
Frequenza 379: Sara
Frequenza 381: Edward
Frequenza 384: Lori
Frequenza 385: Ronald
Frequenza 389: Sean
Frequenza 391: Tyler
Frequenza 394: Tracy
Frequenza 398: Jamie
Frequenza 404: Pamela
Frequenza 405: Zachary
Frequenza 408: Jeremy
Frequenza 415: Kyle
Frequenza 416: Maria
Frequenza 419: Brenda
Frequenza 426: Amber, Sandra
Frequenza 430: Donald
Frequenza 431: Shannon
Frequenza 436: Linda
Frequenza 438: Andrea, Crystal
Frequenza 443: Katherine
Frequenza 445: Tiffany
Frequenza 463: Aaron
Frequenza 465: Adam
Frequenza 469: Benjamin
Frequenza 471: Danielle
Frequenza 475: Brittany, Tammy
Frequenza 476: Patrick
Frequenza 497: Lauren
Frequenza 504: Christine
Frequenza 508: Stephen
Frequenza 510: Gregory
Frequenza 511: Cynthia
Frequenza 512: Megan
Frequenza 550: Kenneth
Frequenza 551: Patricia
Frequenza 563: Samantha
Frequenza 573: Rachel
Frequenza 579: Jacob
Frequenza 582: Julie
Frequenza 602: Susan
Frequenza 606: Christina
Frequenza 643: Emily
Frequenza 654: Paul
Frequenza 674: Brandon
Frequenza 675: Nicholas
Frequenza 681: Jonathan
Frequenza 688: Kelly
Frequenza 699: Scott
Frequenza 710: Karen
Frequenza 714: Rebecca
Frequenza 721: Justin
Frequenza 739: Charles
Frequenza 746: Nicole
Frequenza 776: Laura
Frequenza 789: Heather
Frequenza 802: Ryan
Frequenza 813: Timothy
Frequenza 820: Angela
Frequenza 829: Jeffrey
Frequenza 832: Eric
Frequenza 901: Amy
Frequenza 910: Mary
Frequenza 912: Andrew
Frequenza 916: Richard
Frequenza 932: Anthony
Frequenza 938: Steven
Frequenza 942: Stephanie
Frequenza 953: Kevin
Frequenza 976: Mark
Frequenza 979: Sarah
Frequenza 988: Joshua
Frequenza 989: Thomas
Frequenza 1000: Melissa
Frequenza 1022: Jason
Frequenza 1036: Ashley
Frequenza 1046: Michelle
Frequenza 1053: Elizabeth
Frequenza 1066: Amanda
Frequenza 1094: Kimberly
Frequenza 1111: Brian
Frequenza 1245: Joseph
Frequenza 1296: Daniel
Frequenza 1308: William
Frequenza 1317: Lisa
Frequenza 1355: Jessica
Frequenza 1418: Matthew
Frequenza 1860: Christopher
Frequenza 1877: Robert
Frequenza 1930: John
Frequenza 1932: Jennifer
Frequenza 2058: James
Frequenza 2091: David
Frequenza 2647: Missing
Frequenza 3130: Michael


Stringhe anomale rilevate:
+-------------+----------------+
| Stringa     | Frequenza      |
+=============+================+
| Maximilian  | Frequenza 1    |
+-------------+----------------+
| Jo          | Frequenza 32   |
+-------------+----------------+
| Kristopher  | Frequenza 38   |
+-------------+----------------+
| Alexandria  | Frequenza 58   |
+-------------+----------------+
| Jacqueline  | Frequenza 310  |
+-------------+----------------+
| Christopher | Frequenza 1860 |
+-------------+----------------+

Il valore del percentile minimo (93%) è: 678.3600000000004
Il valore del percentile massimo (100%) è: 3130.0

Frequenze escluse: 675, 674, 654, 643, 606, 602, 582, 579, 573, 563, 551, 550, 512, 511, 510, 508, 504, 497, 476, 475, 471, 469, 465, 463, 445, 443, 438, 436, 431, 430, 426, 419, 416, 415, 408, 405, 404, 398, 394, 391, 389, 385, 384, 381, 379, 370, 364, 357, 356, 351, 349, 348, 347, 344, 341, 340, 339, 338, 337, 334, 333, 332, 326, 325, 323, 321, 316, 312, 310, 308, 305, 303, 302, 301, 295, 294, 289, 288, 287, 283, 278, 277, 273, 272, 266, 263, 259, 258, 257, 255, 254, 253, 251, 247, 245, 243, 242, 240, 238, 235, 232, 229, 228, 225, 224, 222, 220, 216, 214, 212, 207, 202, 200, 199, 198, 196, 195, 194, 192, 191, 189, 188, 187, 186, 185, 183, 181, 179, 178, 177, 176, 173, 172, 171, 169, 168, 167, 164, 163, 162, 161, 159, 158, 157, 154, 150, 147, 146, 145, 144, 143, 140, 139, 138, 137, 135, 134, 133, 131, 130, 129, 128, 126, 125, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 97, 96, 95, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 1
Frequenze mantenute: 3130, 2647, 2091, 2058, 1932, 1930, 1877, 1860, 1418, 1355, 1317, 1308, 1296, 1245, 1111, 1094, 1066, 1053, 1046, 1036, 1022, 1000, 989, 988, 979, 976, 953, 942, 938, 932, 916, 912, 910, 901, 832, 829, 820, 813, 802, 789, 776, 746, 739, 721, 714, 710, 699, 688, 681</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-33-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-33-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p><strong>Here i’ve used a function that i’ve developed for an other project, sadly there are too many frequencies, so it’s a bit a mess, but we still can see that there aren’t any strange values</strong></p>
<div id="cell-61" class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the distribution of the user_first_name column</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>grafici.plot_categorical_column(users, <span class="st">'user_last_name'</span>, <span class="st">"lightblue"</span>, min_percentile<span class="op">=</span><span class="dv">93</span>, max_percentile<span class="op">=</span><span class="dv">100</span>, hide_outliers<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">5</span>), anomaly_threshold<span class="op">=</span><span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Categorie per Frequenza:
Frequenza 24: Good
Frequenza 27: Kidd
Frequenza 28: Brandt
Frequenza 29: Stanton
Frequenza 30: David, Holder, Mata
Frequenza 31: Bird, Sanford
Frequenza 32: Compton, Murillo, Ritter
Frequenza 33: Cooley, Jarvis, Key, Travis
Frequenza 34: Bonilla, Cuevas, Estes, Mayo
Frequenza 35: Andersen, Blankenship, Bright, Moyer, Odom, Werner
Frequenza 36: Beltran, Conway, Joyce, Levy, Mckay, Mercer, Montes, Shea
Frequenza 37: Cowan, Dickson, Esparza, Glass, Hanna, Lutz, Mcneil, Meza, Oconnell, Terrell
Frequenza 38: Baird, Bender, Booker, Chaney, Church, Davila, Donaldson, Haas, Hays, Richmond, Rivers
Frequenza 39: Duarte, Dudley, Galloway, Gay, Hatfield, Horne, Moses, Potts, Proctor, Rubio, Shepard, Vang, Whitney
Frequenza 40: Acevedo, Bernard, Blevins, Cordova, Kaufman, Mcmillan, Mullen, Sampson
Frequenza 41: Barr, Carney, Choi, Daugherty, Ewing, Forbes, Hickman, Mccann, Mccarty, Nixon, Osborn, Riddle, Weeks
Frequenza 42: Ashley, Berger, Blanchard, Cherry, Cooke, Costa, Davies, Hester, Huerta, Krueger, Maynard, Mooney, Schaefer, Villa, Zuniga
Frequenza 43: Arellano, Benitez, Braun, Buck, Clements, Duffy, Durham, Escobar, Ferrell, Haley, Hayden, Herman, Hurley, Johns, Petty, Valentine, Walls, Yu
Frequenza 44: Chung, Crane, Dodson, Finley, Fritz, Gaines, Huber, Levine, Middleton, Rowland, Santana
Frequenza 45: Arroyo, Blackwell, Bolton, Buckley, Cisneros, Dougherty, Downs, Duke, Gamble, Landry, Pugh, Sheppard
Frequenza 46: Barajas, Farley, Frey, Gould, Rangel, Stout, Stuart, Waller, Woodward, Zavala
Frequenza 47: Ali, Ayers, Blackburn, Bradshaw, Branch, Case, Conrad, Ellison, Frost, Golden, Holden, Mckee, Orr, Rush, Schmitt, Spence, Zhang
Frequenza 48: Bentley, Benton, Cantu, Crosby, Hardin, Hinton, Hooper, House, Koch, Krause, Macdonald, Mcconnell, Merritt, Mosley, Novak, Pollard, Rasmussen, Spears, Stark, Tapia, Valencia, Villegas, Wyatt
Frequenza 49: Avery, Benjamin, Bullock, Harrell, Hebert, Howe, Maddox, Mccall, Mcintyre, Mcknight, Riggs, Sosa, Vance, Vaughan, Velazquez
Frequenza 50: Archer, Barry, Gates, Haney, Hobbs, Kaiser, Mayer, Oneill, Ponce, Rich, Sellers, Shah, Wu
Frequenza 51: Andrade, Cabrera, Frederick, Fry, Hahn, Hendrix, Kline, Mcclure, Mcgrath, Mcintosh, Noble, Nolan, Parrish, Pineda, Randolph, Whitehead
Frequenza 52: Bartlett, Bautista, Best, Brennan, Cantrell, Donovan, Fitzpatrick, Herring, Ho, Lucero, Mays, Mcpherson, Meadows, Melendez, Michael, Moon, Pennington, Preston, Rosario, Sexton, Sweeney
Frequenza 53: Bray, Faulkner, Galvan, Harding, Henson, Lester, Lowery, Strong
Frequenza 54: Barron, Burch, Calhoun, Carson, Clay, Coffey, Dorsey, Friedman, Frye, Hendricks, Huang, Irwin, Jacobson, Knox, Lin, Mahoney, Melton, Pace, Peck, Prince, Summers
Frequenza 55: Barrera, Dunlap, Farrell, Gentry, Giles, Keith, Kerr, Knapp, Mcclain, Mcmahon, Odonnell, Reilly, Roach, Savage, Wiley, Winters
Frequenza 56: Arias, Boyer, Boyle, Eaton, Franco, French, Leblanc, Pruitt, Rollins, Velez
Frequenza 57: Allison, Baxter, Bean, Everett, Gallegos, Mathis, Shields, Villarreal, Wilkerson, Woodard
Frequenza 58: Atkins, Decker, Huynh, Kent, Lang, Lynn, Nielsen, Pacheco, Shannon, Sloan, Valenzuela, Villanueva
Frequenza 59: Bradford, Gilmore, Horn, Kemp, Livingston, Madden, Mcfarland, Mclean, Morse, Pitts, Rivas, Stein
Frequenza 60: Abbott, Anthony, Houston, Hull, Ibarra, Ochoa, Patrick, Wilkinson
Frequenza 61: Davenport, Glenn, Greer, Lam, Orozco, Randall, Raymond, Yoder
Frequenza 62: Booth, Bruce, Cameron, Castaneda, Cochran, Heath, Leach, Macias, Mercado, Rocha, Small
Frequenza 63: Beard, Camacho, Lozano, Mccullough, Olsen, Petersen, Salas, Solomon, Ware
Frequenza 64: Ballard, Beasley, Chase, Christian, Conner, Kane, Massey, Morrow, Richard, Roman, Rosales, Roy, Wiggins
Frequenza 65: Bryan, Charles, Dalton, Dyer, Gillespie, Roberson, Serrano, Singleton, Stokes, Suarez
Frequenza 66: Boone, Bridges, Hancock, Jefferson, Marks, Mcdowell, Morton, Phelps, Rowe, Russo, Stephenson, Tanner, Whitaker, Wilcox
Frequenza 67: Burgess, Cline, Conley, Dickerson, Foley, Kirby, Liu, Snow, Solis, Walton
Frequenza 68: Bond, Cain, Collier, Garrison, Hess, Holloway, Larsen, Norton, Pittman
Frequenza 69: Berg, Browning, Delacruz, Dillon, Grimes, Hines, Hurst, Hutchinson, Leon, Nash, Sawyer, Sparks, Velasquez, Vincent
Frequenza 70: Cardenas, Cervantes, Copeland, Hensley, Lindsey, Mathews, Oneal, Skinner, Stafford, Underwood
Frequenza 71: Atkinson, Burnett, English, Fuentes, Huffman, Khan, Kirk, Mckenzie, Nicholson, Robles
Frequenza 72: Adkins, Carey, Deleon, Glover, Hoover, Mora, Shaffer, Zamora
Frequenza 73: Lamb, Moss
Frequenza 74: Briggs, Combs, Dennis, Gibbs, Hodge, Hogan, Huff, Kramer, Marsh, Poole, Pratt, York
Frequenza 75: Bowers, Callahan, Colon, Flowers, Garner, Hammond, Harrington, Humphrey, Li, Mack, Norman, Patton, Rojas
Frequenza 76: Bauer, Chan, Drake, Guerra, Hood, Lara, Miranda, Pope, Shepherd, Townsend, Weiss
Frequenza 77: Brock, Meyers, Roth, Walter
Frequenza 78: Buchanan, Carrillo, Hartman, Mcguire, Oconnor, Wall
Frequenza 79: Malone, Owen, Salinas
Frequenza 80: Aguirre, Bass, Bowen, Joseph, Mcbride, Monroe, Saunders, Schroeder, Wilkins
Frequenza 81: Barton, Calderon, Clayton, Curry, Flynn, Tate, Trevino, Yates
Frequenza 82: Mclaughlin, Mejia, Trujillo, Webster
Frequenza 83: Francis, Gill, Miles, Moody
Frequenza 84: Christensen, Erickson, Farmer, Lyons, Montoya, Tyler, Wise
Frequenza 85: Campos, Clarke, Cobb, Goodwin, Hubbard, Mccormick, Short
Frequenza 86: Duran, Juarez, Reeves, Stevenson, Wolf
Frequenza 87: Avila, Ball, Brady, Fischer, Hodges, Marquez, Parsons
Frequenza 88: Osborne, Singh
Frequenza 89: Daniel, Lloyd, Mann, Mcgee, Park, Paul, Quinn
Frequenza 90: Casey, Chang, Floyd, Frank, Holt, Molina, Padilla, Strickland
Frequenza 91: Fleming, Hampton, Hardy, Navarro, Yang
Frequenza 92: Acosta, Bush, Gallagher, Le, Mueller, Newton
Frequenza 93: Barber, Higgins, Maxwell, Potter, Vaughn
Frequenza 94: Baldwin, Blake, Craig, Figueroa, Guerrero, Terry, Waters
Frequenza 95: Fields, Pham, Wang
Frequenza 96: Ayala, Cummings, Fitzgerald, Todd
Frequenza 97: Cross, Doyle, Leonard, Ramsey
Frequenza 98: Banks, Dominguez, Graves, Harmon, Manning, Rodgers, Sherman
Frequenza 99: Cannon, Cortez, Luna
Frequenza 100: Becker, Goodman, Lowe, Moran, Reese, Robbins
Frequenza 101: Blair, Hale, Mckinney, Mullins, Norris, Watts
Frequenza 102: Dawson, Frazier, Ingram, Page
Frequenza 103: Byrd, Cohen, Gross, Haynes, Horton
Frequenza 104: Chandler, Lambert, Logan, Pena, Wolfe
Frequenza 105: Warner
Frequenza 106: Fletcher, Simon
Frequenza 107: Caldwell, Griffith, Sandoval, Wade
Frequenza 108: Klein, Love, Sharp, Vazquez
Frequenza 109: Mccarthy, Schultz, Sutton, Swanson, Thornton, Zimmerman
Frequenza 110: Keller, Neal, Santos, Steele
Frequenza 111: Barker, Espinoza
Frequenza 112: Shelton, Soto
Frequenza 113: Douglas, May
Frequenza 114: Brewer
Frequenza 115: Maldonado, Reid
Frequenza 116: Benson, Jennings, Walsh
Frequenza 117: Rhodes, Vega
Frequenza 118: Contreras, Santiago
Frequenza 119: Gregory, Hopkins, Powers
Frequenza 120: Alvarado, Weber
Frequenza 121: Nunez, Valdez
Frequenza 122: Bates
Frequenza 123: Barrett, Delgado, Holland
Frequenza 124: Obrien
Frequenza 125: Parks
Frequenza 126: Bowman
Frequenza 127: Bishop, Lucas
Frequenza 128: George
Frequenza 129: Carr, Schwartz, Walters
Frequenza 130: Fowler, Ortega
Frequenza 131: Curtis, Davidson, Estrada, Sims, Wong
Frequenza 132: Beck, Berry, Mcdaniel, Pearson
Frequenza 133: Chen, Jensen, Schneider
Frequenza 134: Fuller, Stanley
Frequenza 135: Barnett, Burton, Chambers, Franklin, Oliver
Frequenza 138: Gilbert, Lynch, Rios
Frequenza 139: Dean, Lawson
Frequenza 141: Day, Hanson, Newman, Richards
Frequenza 142: Mendez, Welch
Frequenza 143: Williamson
Frequenza 144: Munoz
Frequenza 145: Aguilar, Lawrence, Montgomery
Frequenza 146: Grant
Frequenza 147: Mccoy, Wheeler
Frequenza 149: Greene
Frequenza 150: Carlson, Harvey, Matthews, Morrison, Salazar
Frequenza 151: Hawkins, Larson, Watkins
Frequenza 152: Garrett
Frequenza 153: Chapman, Dunn, Hansen, Jacobs
Frequenza 154: Burke, Harper, Little, Vargas
Frequenza 155: Andrews
Frequenza 156: Gardner, Johnston, Lane
Frequenza 157: Stephens
Frequenza 158: Knight, Ray
Frequenza 159: Fernandez, Fox, Perkins
Frequenza 160: Arnold, Robertson
Frequenza 161: Armstrong, Riley, Willis
Frequenza 162: Howell
Frequenza 163: Austin, Duncan
Frequenza 165: Herrera
Frequenza 166: Garza, Tran
Frequenza 167: Hudson, Palmer
Frequenza 168: Cunningham, Silva
Frequenza 169: Bradley, Guzman, Hart, Weaver
Frequenza 170: Carroll
Frequenza 171: Daniels
Frequenza 172: Pierce
Frequenza 173: Elliott
Frequenza 175: Holmes, Peters
Frequenza 176: Castro, Patel, Rose
Frequenza 179: Hunt, Schmidt
Frequenza 180: Carpenter, Hoffman
Frequenza 181: Boyd
Frequenza 182: Freeman
Frequenza 183: Mills
Frequenza 184: Spencer, Vasquez
Frequenza 186: Gordon, Payne, Simpson
Frequenza 189: Meyer, Shaw
Frequenza 190: Hicks
Frequenza 191: Wagner
Frequenza 192: Black, Hunter, Ryan
Frequenza 193: Burns, Ferguson, Medina
Frequenza 194: Nichols, Warren
Frequenza 195: Castillo, Dixon, Mendoza
Frequenza 196: Romero, Webb
Frequenza 198: Ellis, Jimenez
Frequenza 199: Henry
Frequenza 202: Snyder
Frequenza 203: Rice, Woods
Frequenza 205: Kelley
Frequenza 206: Washington, Wells
Frequenza 207: Stone
Frequenza 208: Mason
Frequenza 209: Moreno
Frequenza 211: Griffin, Tucker
Frequenza 213: Kennedy, Marshall
Frequenza 216: Crawford, Mcdonald
Frequenza 217: Owens
Frequenza 218: Porter
Frequenza 219: Olson
Frequenza 220: Ruiz
Frequenza 223: Alvarez, Gibson
Frequenza 225: Ford
Frequenza 226: Murray
Frequenza 228: Stevens
Frequenza 229: Bryant
Frequenza 231: Hayes
Frequenza 232: Cole
Frequenza 233: Patterson
Frequenza 234: Harrison
Frequenza 235: Hamilton
Frequenza 236: Chavez
Frequenza 237: Jordan
Frequenza 238: Coleman
Frequenza 239: Gonzales
Frequenza 241: Ortiz, West
Frequenza 243: Ramos
Frequenza 244: Alexander
Frequenza 250: Barnes, Butler, Simmons
Frequenza 251: Cruz
Frequenza 252: Reynolds, Wallace
Frequenza 254: Gutierrez
Frequenza 255: Graham, Kim
Frequenza 259: Henderson
Frequenza 260: Powell
Frequenza 261: Morales, Sullivan
Frequenza 263: Fisher
Frequenza 267: Russell
Frequenza 268: Perry
Frequenza 272: Jenkins
Frequenza 275: Hughes, Long
Frequenza 276: Ross
Frequenza 277: Price, Wood
Frequenza 280: Sanders
Frequenza 286: Reyes
Frequenza 287: Myers
Frequenza 292: Foster
Frequenza 294: Richardson
Frequenza 298: Bennett
Frequenza 300: Brooks, Gray
Frequenza 303: Watson
Frequenza 307: Diaz
Frequenza 309: Reed, Ward
Frequenza 311: James
Frequenza 318: Bailey
Frequenza 319: Bell
Frequenza 331: Cox
Frequenza 333: Gomez
Frequenza 343: Howard, Morris
Frequenza 346: Morgan
Frequenza 350: Peterson
Frequenza 351: Cooper
Frequenza 352: Kelly, Rogers
Frequenza 356: Nguyen
Frequenza 380: Collins
Frequenza 383: Edwards
Frequenza 385: Cook
Frequenza 388: Murphy
Frequenza 390: Torres
Frequenza 392: Evans
Frequenza 399: Rivera
Frequenza 404: Flores
Frequenza 408: Stewart
Frequenza 428: Turner
Frequenza 431: Parker
Frequenza 436: Campbell
Frequenza 448: Carter
Frequenza 454: Roberts
Frequenza 468: Phillips
Frequenza 477: Mitchell
Frequenza 494: Ramirez
Frequenza 506: Scott
Frequenza 512: Nelson
Frequenza 522: Hill
Frequenza 540: Sanchez
Frequenza 545: Adams
Frequenza 556: Hall
Frequenza 559: Baker
Frequenza 580: Wright
Frequenza 587: Green, Robinson
Frequenza 595: Allen
Frequenza 596: King
Frequenza 603: Young
Frequenza 620: Perez
Frequenza 624: Walker
Frequenza 662: Lewis
Frequenza 738: Lopez
Frequenza 743: Clark
Frequenza 770: Lee
Frequenza 787: Harris
Frequenza 792: Gonzalez
Frequenza 800: Thompson
Frequenza 815: White
Frequenza 827: Hernandez
Frequenza 831: Jackson
Frequenza 833: Martin
Frequenza 859: Moore
Frequenza 887: Taylor
Frequenza 895: Thomas
Frequenza 955: Anderson
Frequenza 970: Wilson
Frequenza 987: Rodriguez
Frequenza 991: Martinez
Frequenza 1082: Garcia
Frequenza 1320: Davis
Frequenza 1460: Miller
Frequenza 1632: Brown
Frequenza 1678: Jones
Frequenza 1818: Williams
Frequenza 2282: Johnson
Frequenza 2615: Missing
Frequenza 3019: Smith


Stringhe anomale rilevate:
+-------------+--------------+
| Stringa     | Frequenza    |
+=============+==============+
| Blankenship | Frequenza 35 |
+-------------+--------------+
| Yu          | Frequenza 43 |
+-------------+--------------+
| Wu          | Frequenza 50 |
+-------------+--------------+
| Fitzpatrick | Frequenza 52 |
+-------------+--------------+
| Ho          | Frequenza 52 |
+-------------+--------------+
| Li          | Frequenza 75 |
+-------------+--------------+
| Christensen | Frequenza 84 |
+-------------+--------------+
| Le          | Frequenza 92 |
+-------------+--------------+

Il valore del percentile minimo (93%) è: 318.0
Il valore del percentile massimo (100%) è: 3019.0

Frequenze escluse: 311, 309, 307, 303, 300, 298, 294, 292, 287, 286, 280, 277, 276, 275, 272, 268, 267, 263, 261, 260, 259, 255, 254, 252, 251, 250, 244, 243, 241, 239, 238, 237, 236, 235, 234, 233, 232, 231, 229, 228, 226, 225, 223, 220, 219, 218, 217, 216, 213, 211, 209, 208, 207, 206, 205, 203, 202, 199, 198, 196, 195, 194, 193, 192, 191, 190, 189, 186, 184, 183, 182, 181, 180, 179, 176, 175, 173, 172, 171, 170, 169, 168, 167, 166, 165, 163, 162, 161, 160, 159, 158, 157, 156, 155, 154, 153, 152, 151, 150, 149, 147, 146, 145, 144, 143, 142, 141, 139, 138, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125, 124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112, 111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 24
Frequenze mantenute: 3019, 2615, 2282, 1818, 1678, 1632, 1460, 1320, 1082, 991, 987, 970, 955, 895, 887, 859, 833, 831, 827, 815, 800, 792, 787, 770, 743, 738, 662, 624, 620, 603, 596, 595, 587, 580, 559, 556, 545, 540, 522, 512, 506, 494, 477, 468, 454, 448, 436, 431, 428, 408, 404, 399, 392, 390, 388, 385, 383, 380, 356, 352, 351, 350, 346, 343, 333, 331, 319, 318</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-34-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-34-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Sorry for the rough visualization of all this info, but i can’t spend time now fixing the graph</p>
<p>Even here we can se that the anomaly forest can’t find anything strange</p>
<div id="cell-63" class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>users[<span class="st">'gender'</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'bar'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-35-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We already replaced the “data layer field missing value” in the gender column</p>
<p>The Other value is really unbalanced</p>
<div id="cell-65" class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get a list of all the domains used in the email column</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>users[<span class="st">'email'</span>].<span class="bu">str</span>.split(<span class="st">'@'</span>).<span class="bu">str</span>[<span class="dv">1</span>].value_counts().plot(kind<span class="op">=</span><span class="st">'pie'</span>, figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-36-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>There’s no <span class="citation" data-cites="icloud.com">@icloud.com</span>, interesting</p>
<p>Everything seems right</p>
</section>
<section id="null-analysis-2" class="level3">
<h3 class="anchored" data-anchor-id="null-analysis-2">2.3.2) Null analysis</h3>
<div id="cell-69" class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>users.shape[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="36">
<pre><code>138678</code></pre>
</div>
</div>
<div id="cell-70" class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># count the null values</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>users.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>customer_id         840
user_first_name    2647
user_last_name     2615
gender              830
email              2729
dtype: int64</code></pre>
</div>
</div>
<div id="cell-71" class="cell" data-execution_count="38">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check how many rows have the customer_id and the gender as null</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(users[(users[<span class="st">'customer_id'</span>].isnull()) <span class="op">&amp;</span> (users[<span class="st">'gender'</span>].isnull())])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="38">
<pre><code>544</code></pre>
</div>
</div>
<p>So if we drop the rows with customer_id as null, we are going to lose 286 genders info out of 138678 rows, that’s not bad</p>
<div id="cell-73" class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop the rows with the customer_id null</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>users <span class="op">=</span> users.dropna(subset<span class="op">=</span>[<span class="st">'customer_id'</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If needed later we can impute the nans for now we can save it</p>
<div id="cell-75" class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># save the cleaned data</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>users.to_csv(<span class="st">'Cleaned_Data/users.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="visits" class="level2">
<h2 class="anchored" data-anchor-id="visits">2.4) Visits</h2>
<ul>
<li><code>visit_id</code>: Unique identifier for the visit.</li>
<li><code>customer_id</code>: Identifier for the user who made the visit.</li>
<li><code>start_timestamp</code>: Timestamp when the visit started (website entry or dealership entry).</li>
<li><code>end_timestamp</code>: Timestamp when the visit ended.</li>
<li><code>visit_type</code>: Type of visit (e.g., purchasing, car configuration, testing).</li>
<li><code>transaction_id</code>: purchase identifier for purchasing visits.</li>
</ul>
<div id="cell-78" class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>visits.shape</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>(438587, 6)</code></pre>
</div>
</div>
<div id="cell-79" class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>visits.head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">visit_id</th>
<th data-quarto-table-cell-role="th">customer_id</th>
<th data-quarto-table-cell-role="th">start_timestamp</th>
<th data-quarto-table-cell-role="th">end_timestamp</th>
<th data-quarto-table-cell-role="th">visit_type</th>
<th data-quarto-table-cell-role="th">transaction_id</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>7f94232d-9cca-4893-aebe-9a267a752f87</td>
<td>de5323eb-5e01-481f-b73a-bb78af953894</td>
<td>2023-04-18 10:51:24.477465</td>
<td>2023-04-18 11:46:26.893492</td>
<td>car configuration</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>dcb32330-15b0-4fd1-b376-9b9335fee7f9</td>
<td>15dcef30-b549-447b-8809-229c9de8526b</td>
<td>2021-03-03 17:54:25.117599</td>
<td>2021-03-03 18:07:25.117599</td>
<td>viewing</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>8b02d675-1365-45bc-af64-61ef9e79149c</td>
<td>3b656455-1690-47d9-b7ad-9e0aaa3bb229</td>
<td>2023-07-07 13:09:00.000000</td>
<td>2023-07-07 13:19:00.000000</td>
<td>purchasing</td>
<td>d1bfe5f5-edc1-4148-8eb0-8127dd3b52c1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>bdfc7048-adc5-4da7-a37a-4f9d90cf6436</td>
<td>c583c671-2f8a-47f3-9460-bd444b1811c8</td>
<td>2023-09-14 11:25:12.820271</td>
<td>2023-09-14 12:20:15.523626</td>
<td>car configuration</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>2ad3a1e1-0b9c-417f-95f7-70607b0fe96e</td>
<td>da8268d8-4e81-4538-bf1d-836ac4d5b155</td>
<td>2020-12-04 19:15:41.833927</td>
<td>2020-12-04 19:27:41.833927</td>
<td>car configuration</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>e312debd-3da7-4b09-adf5-7584f9757a64</td>
<td>ddc7b33e-2ce2-4d4e-a9ae-af658297b3f9</td>
<td>2023-05-08 08:48:04.039144</td>
<td>2023-05-08 09:43:12.364381</td>
<td>viewing</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">6</td>
<td>0cb32f18-13df-46a3-a6ad-e75e52752c97</td>
<td>74da1e99-b941-41fc-80c0-81454f24a6fa</td>
<td>2022-06-17 09:07:00.000000</td>
<td>2022-06-17 09:29:00.000000</td>
<td>purchasing</td>
<td>5f30bffd-d546-4787-9dc9-9dab00a43719</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">7</td>
<td>1bd012ab-6077-4181-ad90-3c014bea260b</td>
<td>9008d1e1-c4d3-48fa-b9c4-3bcf22d9761b</td>
<td>2023-10-15 09:22:21.711984</td>
<td>2023-10-15 10:17:29.350944</td>
<td>viewing</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">8</td>
<td>fa474cb9-dac4-417d-9739-7d351cc8a10e</td>
<td>84d4cdb2-6a5a-4415-808e-e20b02a1788a</td>
<td>2021-10-28 09:21:22.366154</td>
<td>2021-10-28 10:22:22.366154</td>
<td>viewing</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">9</td>
<td>d2d29fbf-39bc-490c-b29c-41f388f20dd1</td>
<td>dbdc3442-018d-4bd1-ae3c-ad8c5d72588a</td>
<td>2023-09-09 16:50:29.075540</td>
<td>2023-09-09 17:00:29.075540</td>
<td>viewing</td>
<td>NaN</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="data-checks-3" class="level3">
<h3 class="anchored" data-anchor-id="data-checks-3">2.4.1) Data checks</h3>
<div id="cell-81" class="cell" data-execution_count="43">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check any strange values in the visit_id column</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>visits[<span class="op">~</span>visits[<span class="st">'visit_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"visit_id"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">
<pre><code>Series([], Name: count, dtype: int64)</code></pre>
</div>
</div>
<div id="cell-82" class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check any strange values in the customer_id column</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>visits[<span class="op">~</span>visits[<span class="st">'customer_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"customer_id"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>Series([], Name: count, dtype: int64)</code></pre>
</div>
</div>
<div id="cell-83" class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check any strange values in the customer_id column</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>visits[<span class="op">~</span>visits[<span class="st">'transaction_id'</span>].fillna(<span class="st">''</span>).<span class="bu">str</span>.contains(<span class="vs">r'[a-z0-9]</span><span class="sc">{8}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{4}</span><span class="vs">-[a-z0-9]</span><span class="sc">{12}</span><span class="vs">'</span>)][<span class="st">"transaction_id"</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">
<pre><code>Series([], Name: count, dtype: int64)</code></pre>
</div>
</div>
<div id="cell-84" class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># creating a new column "visit_duration_time" that is the difference between the start_timestamp and the end_timestamp</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">'start_timestamp'</span>] <span class="op">=</span> pd.to_datetime(visits[<span class="st">'start_timestamp'</span>])</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">'end_timestamp'</span>] <span class="op">=</span> pd.to_datetime(visits[<span class="st">'end_timestamp'</span>])</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">'visit_duration_time'</span>] <span class="op">=</span> visits[<span class="st">'end_timestamp'</span>] <span class="op">-</span> visits[<span class="st">'start_timestamp'</span>]</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="co"># check the distribution of the visit_duration_time column</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">'visit_duration_time'</span>].dt.total_seconds().plot(kind<span class="op">=</span><span class="st">'box'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-47-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>We can see that there’s something strange with the negative values</p>
<div id="cell-86" class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print the rows that have the end_timestamp &lt; than start_timestamp</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>visits[visits[<span class="st">'end_timestamp'</span>] <span class="op">&lt;</span> visits[<span class="st">'start_timestamp'</span>]].head(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="47">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">visit_id</th>
<th data-quarto-table-cell-role="th">customer_id</th>
<th data-quarto-table-cell-role="th">start_timestamp</th>
<th data-quarto-table-cell-role="th">end_timestamp</th>
<th data-quarto-table-cell-role="th">visit_type</th>
<th data-quarto-table-cell-role="th">transaction_id</th>
<th data-quarto-table-cell-role="th">visit_duration_time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">54</td>
<td>76cbcc77-5dce-42c7-ad18-be0aaf14c4c0</td>
<td>4fcab3f2-8ac7-407e-8e3e-4da229d76384</td>
<td>2022-07-03 09:17:02.504868</td>
<td>2022-07-03 09:09:02.504868</td>
<td>testing</td>
<td>NaN</td>
<td>-1 days +23:52:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">65</td>
<td>1ad01c01-929f-4b24-a87b-c7d920bab6b8</td>
<td>f5eba840-47f3-4502-92de-594e03285508</td>
<td>2023-04-30 18:34:49.603612</td>
<td>2023-04-30 18:30:49.603612</td>
<td>viewing</td>
<td>NaN</td>
<td>-1 days +23:56:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">130</td>
<td>6d0af211-ce8e-4e72-9917-62b3543a4613</td>
<td>9b74e1eb-45ed-4680-8e16-e58db216fa2d</td>
<td>2023-08-12 20:05:00.000000</td>
<td>2023-08-12 20:03:00.000000</td>
<td>purchasing</td>
<td>f1b05953-799c-4930-b399-7442e3380758</td>
<td>-1 days +23:58:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">255</td>
<td>8563c3b8-e48e-42a9-bb3a-56d9c295038f</td>
<td>eeacac9c-8c61-4eac-af16-dee0d63381ae</td>
<td>2021-08-07 19:06:47.842724</td>
<td>2021-08-07 18:57:47.842724</td>
<td>testing</td>
<td>NaN</td>
<td>-1 days +23:51:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">345</td>
<td>f52d6e30-97ca-4c6d-aff5-ddb2ee990825</td>
<td>27984fe4-53ef-4cd5-9f9b-7491a4718c10</td>
<td>2022-12-05 09:13:57.073838</td>
<td>2022-12-05 09:09:57.073838</td>
<td>testing</td>
<td>NaN</td>
<td>-1 days +23:56:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">387</td>
<td>2c084bea-b255-4701-927f-96770008ff12</td>
<td>ad2f785a-551a-476e-ad8b-cefedf775027</td>
<td>2023-02-16 19:55:20.349139</td>
<td>2023-02-16 19:54:20.349139</td>
<td>viewing</td>
<td>NaN</td>
<td>-1 days +23:59:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">932</td>
<td>24c76e44-56da-4431-a0ac-d203420fb6bc</td>
<td>f2332d3c-def5-4b2f-bcb8-02f6687051d8</td>
<td>2021-10-22 11:14:23.124399</td>
<td>2021-10-22 10:56:23.124399</td>
<td>viewing</td>
<td>NaN</td>
<td>-1 days +23:42:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1009</td>
<td>444fac22-8df0-4065-b913-b9c95923d7d0</td>
<td>265413dc-d2e7-47a6-b80a-cc03d2eaa406</td>
<td>2023-12-06 19:50:42.091701</td>
<td>2023-12-06 19:46:42.091701</td>
<td>viewing</td>
<td>NaN</td>
<td>-1 days +23:56:00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">1041</td>
<td>5fa67a8e-e843-471c-885a-2e991ca11187</td>
<td>a8809951-11b1-47eb-a147-53b9c7b172e1</td>
<td>2024-01-13 20:39:00.000000</td>
<td>2024-01-13 20:37:00.000000</td>
<td>purchasing</td>
<td>152c991a-dcf8-4018-9faf-053457fdb868</td>
<td>-1 days +23:58:00</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1078</td>
<td>b61bf4e7-babb-4297-8da6-a3fa6a202b44</td>
<td>24e7963c-0b92-4ad0-aa38-03bc8aacdd42</td>
<td>2022-10-24 18:55:08.629538</td>
<td>2022-10-24 18:45:08.629538</td>
<td>viewing</td>
<td>NaN</td>
<td>-1 days +23:50:00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>it seems that an error occurred, we can just take the absolute values of the difference (in a real world scenario it would be useful to understand why this happen, for now we’re just going to proceed)</p>
<div id="cell-88" class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">'visit_duration_time'</span>] <span class="op">=</span> <span class="bu">abs</span>(visits[<span class="st">'end_timestamp'</span>] <span class="op">-</span> visits[<span class="st">'start_timestamp'</span>])</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check the distribution of the visit_duration_time column</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">'visit_duration_time'</span>].dt.total_seconds().plot(kind<span class="op">=</span><span class="st">'box'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-49-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-89" class="cell" data-execution_count="49">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># visit type value counts</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>visits[<span class="st">"visit_type"</span>].value_counts().plot(kind<span class="op">=</span><span class="st">"bar"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="%5BSTEP%201%5D%20Data%20Cleaning_files/figure-html/cell-50-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-90" class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the percentage of transaction_id nans</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Percentage of avaiable transaction_id: </span><span class="sc">{</span>(<span class="dv">1</span><span class="op">-</span>visits[<span class="st">'transaction_id'</span>].isnull().mean()) <span class="op">*</span> <span class="dv">100</span><span class="sc">:.2f}</span><span class="ss">%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Percentage of avaiable transaction_id: 17.05%</code></pre>
</div>
</div>
</section>
<section id="null-analysis-3" class="level3">
<h3 class="anchored" data-anchor-id="null-analysis-3">2.4.2) Null analysis</h3>
<div id="cell-92" class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># print the nulls</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>visits.isnull().<span class="bu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="51">
<pre><code>visit_id                    0
customer_id                 0
start_timestamp             0
end_timestamp               0
visit_type                  0
transaction_id         363807
visit_duration_time         0
dtype: int64</code></pre>
</div>
</div>
<p>Everything seems allright, we can save it</p>
<div id="cell-94" class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># save the cleaned data</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>visits.to_csv(<span class="st">'./Cleaned_Data/visits.csv'</span>, index<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>